### ISSUE TITLE
Possible for sayHello() to return String ?

### ISSUE THREAD

**Issue by cflorion** [vgorloff/swift-everywhere-toolchain#104]
Hi ! 
I tried the toolchain and it works well. I'm even surprised how easy it is to set up. So thanks a ton ! :)
I am now learning how to work with JNI and I've had a problem from the beginning.
When i take the sample project and I modify the sayHello() method to return a String instead of an Int, it crashes instantly without any error message. I changed the type on the Kotlin side as well. It seemed to be a simple change so I must have misunderstood something. I
Is this possible to pass a String from Swift to JNI ?

Thanks

**Comment by cflorion** [comment]
I actually have an error output:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.home.hello_ndk, PID: 18004
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "objc_autoreleaseReturnValue" referenced by "/data/app/~~KqxlQwqa3TUqTqGewhdxaw==/com.home.hello_ndk-7-pMpv4TptG-2zyxuoccOw==/base.apk!/lib/x86/libHelloJNICore.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.home.helloNDK.SwiftLib.<clinit>(SwiftLib.java:6)
        at com.home.helloNDK.MainActivity$1.onClick(MainActivity.java:54)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by vgorloff** [comment]
Hi,

Should be possible. I have to check.

FYI: At the moment I am updating sample project to do more interesting things than "hello world". To simplify Swift <-> Java communication the `protobuf` will be used.

- https://developers.google.com/protocol-buffers/docs/javatutorial#writing-a-message
- https://github.com/apple/swift-protobuf

**Comment by cflorion** [comment]
Wow that's amazing news !

**Comment by vgorloff** [comment]
The "Protocol buffers" example added to https://github.com/vgorloff/swift-everywhere-samples repository.
Example shows how to send/receive complex data to/from Kotlin/Swift.

**Comment by vgorloff** [comment]
It is theoretically doable, but making such bridge via JNI will be nightmare. I was thinking to update example without using JNI at all and using FFI instead.

Some info:

- https://github.com/jnr/jnr-ffi
- https://stackoverflow.com/questions/36819679/node-fficall-c-lib-with-callback-function
- https://github.com/ffi/ffi/wiki/Callbacks (Ruby example)
